### ISSUE TITLE
Uncaught (in promise) ReferenceError: alert is not defined

### ISSUE THREAD

**Issue by dejanceltra** [3buson/forgetMeNot#3]
I got:
`Uncaught (in promise) ReferenceError: alert is not defined`
when `fetch` failed.

<img width="643" alt="Screenshot 2024-02-21 at 15 02 03" src="https://github.com/3buson/forgetMeNot/assets/90892252/3480719e-6eb3-46b5-a215-150cbf288f4c">

---

StackOverflow says that alert is not defined in a service worker per specification. 😅

**Comment by 3buson** [comment]
Whoops! Thanks for reporting, I'll check this in the next few days.

**Comment by 3buson** [comment]
Fixed in #4
